on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cmake-build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: cmake build
        run: ./build.sh
      - name: cmake test
        run: ./test.sh
